# Generated by Django 5.1 on 2024-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['vehicle'], name='app_status_vehicle_1cefa7_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status'], name='app_status_status_182295_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status', 'vehicle'], name='app_status_status_fd8ba0_idx'),
        ),
    ]
