# Generated by Django 5.1 on 2024-08-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.asset'),
        ),
    ]
